# Generated by Django 4.2.4 on 2023-09-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructor",
            name="department",
            field=models.CharField(
                choices=[
                    ("Science", "Science"),
                    ("Arts", "Arts"),
                    ("Computer Science", "Computer Science"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.CharField(
                choices=[
                    ("Computer Science", "Computer Science"),
                    ("Engineering", "Engineering"),
                    ("Business", "Business"),
                ],
                max_length=20,
            ),
        ),
    ]
