# Generated by Django 4.2.4 on 2023-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_instructor_department_alter_student_major"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("instructor", "Instructor"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=20,
            ),
        ),
    ]
